language: bash

before_script:
  - curl -OL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - gunzip hugo*.tar.gz
  - chmod 755 hugo

install:
  - curl -LO https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_0.55.4_Linux-64bit.deb
  - sudo dpkg -i hugo_0.55.4_Linux-64bit.deb

script:
  - hugo
env:
  global:
    - GITHUB_REPO: "techprimers/techprimers.github.io"

deploy:
  provider: pages
  script: ./deploy.sh
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master